services:
  - type: web
    name: qscope-backend
    runtime: python
    buildCommand: |
      cd qscope-backend &&
      pip install --upgrade pip &&
      pip install -r requirements.txt
    startCommand: |
      cd qscope-backend &&
      gunicorn --bind 0.0.0.0:$PORT run:app
    plan: free
    region: oregon
    branch: main
    rootDir: .
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MAX_QUBITS
        value: 8
      - key: MAX_GATES_PER_CIRCUIT
        value: 50
      - key: SIMULATION_TIMEOUT
        value: 15
      - key: DEFAULT_DIFFICULTY_LEVEL
        value: beginner
      - key: ENABLE_DETAILED_EXPLANATIONS
        value: True
      - key: QCHAT_MAX_RETRIES
        value: 5
      - key: QCHAT_TIMEOUT
        value: 60
      - key: QCHAT_CIRCUIT_BREAKER_THRESHOLD
        value: 3
      - key: QCHAT_CIRCUIT_BREAKER_TIMEOUT
        value: 60
      - key: OPENROUTER_API_KEY
        value: your-openrouter-api-key-here
    # Add these in Render dashboard:
    # SECRET_KEY: Generate a secure random string
    # CORS_ORIGINS: Your Netlify app URL (e.g., https://your-netlify-app.netlify.app)